Models/District.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace NityCityWeb.Models
{
    public class District
    {
        public int DistrictId { get; set; }
        public string DistrictName { get; set; }
        public string Description { get; set; }
        public string ImageOne { get; set; }
        public string ImageTwo { get; set; }
        public string BackImage { get; set; }
        public string ImageMap { get; set; }
        public int? TotalStars { get; set; }
        public int? TotalVotes { get; set; }

        public string ShortDescription { get; set; }

        [NotMapped]
        public List<string> ImageUrls { get; set; }

        [NotMapped] // This property is calculated and not stored in the database
        public decimal? AverageRating
        {
            get
            {
                if (TotalVotes.HasValue && TotalVotes > 0)
                {
                    return TotalStars / (decimal)TotalVotes;
                }
                return null; // No rating if there are no votes
            }
        }
    }
}

Controllers/DistrictController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NityCityWeb.db;
using NityCityWeb.Models;
using System.Threading.Tasks;

namespace NityCityWeb.Controllers
{
    public class DistrictController : Controller
    {
        private readonly NightCityContext _context;
        private readonly IWebHostEnvironment _env;

        public DistrictController(NightCityContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public async Task<IActionResult> Index() 
        {
            var districts = await _context.Districts.ToListAsync();
            return View(districts);
        }

        private bool ImageExists(string imageUrl)
        {
            // Get the absolute path of the image
            var imagePath = Path.Combine(_env.WebRootPath, imageUrl.TrimStart('/'));
            return System.IO.File.Exists(imagePath);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var district = await _context.Districts.FirstOrDefaultAsync(m => m.DistrictId == id);

            if (district == null)
            {
                return NotFound();
            }

            // Prepare the list of image names 
            var imageNames = new List<string> { "One", "Two" };
            district.ImageUrls = new List<string>();

            foreach (var imageName in imageNames)
            {
                string formattedDistrictName = district.DistrictName.Replace(" ", "");
                string imageUrl = $"/Pictures/District/{district.DistrictName}/{formattedDistrictName}_Image_{imageName}.jpg";
                // Check if the image exists, and if so, add it to the list
                if (ImageExists(imageUrl))
                {
                    district.ImageUrls.Add(imageUrl);
                }
            }

            var districts = await _context.Districts.OrderBy(d => d.DistrictId).ToListAsync();
            int currentIndex = districts.FindIndex(d => d.DistrictId == id);
            int totalDistricts = districts.Count;

            int prevId = currentIndex > 0 ? districts[currentIndex - 1].DistrictId : districts[totalDistricts - 1].DistrictId;
            int nextId = currentIndex < totalDistricts - 1 ? districts[currentIndex + 1].DistrictId : districts[0].DistrictId;

            ViewBag.PrevId = prevId;
            ViewBag.NextId = nextId;

            return View(district);
        }

    }
}

Views/District/Details.cshtml
@model NityCityWeb.Models.District

@{
    ViewData["Title"] = "District Details";
}
<!-- CSS Stylesheets-->
<link rel="stylesheet" href="~/css/cyberpunk-css-main/cyberpunk.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/district.css" asp-append-version="true">

<div id="districtBackground" class="district-bg" data-district-name="@Model.DistrictName.Replace(" ", "")" style="background-image: url('@Url.Content("~/Pictures/District/" + Uri.EscapeDataString(Model.DistrictName) + "/" + Uri.EscapeDataString(Model.ImageOne))');">
    <!-- Overlay -->
    <div class="district-overlay"></div>
    <!-- Content -->
    <div class="hedistrictro-content text-center">
        <h1 class="display-4 cyber-h fg-black oxanium-font">@Model.DistrictName</h1>
    </div>
</div>

<!-- Left Arrow Button -->
<a href="@Url.Action("Details", "District", new { id = ViewBag.PrevId })" class="arrow-button left-arrow">&#x25C0;</a>
<div>
    <h2 class="cyber-h oxanium-font">Details</h2>
    <div>
        <h4 class="cyber-h oxanium-font">District</h4>
        <hr />
        <dl class="row oxanium-font">
            <dt class="col-sm-2">
                Description
            </dt>
            <dd class="col-sm-10">
                @Model.Description
            </dd>
            <dt class="col-sm-2">
                Map
            </dt>
            <dd class="col-sm-10">
                <div class="image-container">
                    <img src="@($"/Pictures/District/{Uri.EscapeDataString(Model.DistrictName)}/{Uri.EscapeDataString(Model.ImageMap)}")" alt="Image of @Model.DistrictName" />
                </div>
            </dd>
            <!-- Add more details as needed -->
        </dl>
    </div>
    <div>
        <br/>
        <a href="@Url.Action("Index", "District")" class="cyber-button bg-red fg-white">Back to List</a>
        <br />
    </div>
</div>

<!-- Right Arrow Button -->
<a href="@Url.Action("Details", "District", new { id = ViewBag.NextId })" class="arrow-button right-arrow">&#x25B6;</a>
<script>
    var imageUrls = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model.ImageUrls));
</script>
<script src="~/js/district-details.js" asp-append-version="true"></script>

Views/District/Index.cshtml
@model IEnumerable<NityCityWeb.Models.District>

@{
    ViewData["Title"] = "Districts";
}
<!-- CSS Stylesheets-->
<link rel="stylesheet" href="~/css/cyberpunk-css-main/cyberpunk.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/district.css" asp-append-version="true">

<h1 class="cyber-h fg-red oxanium-font">@ViewData["Title"]</h1>

<div class="districts-container">
    @foreach (var district in Model)
    {
        <h2 class="display-4 cyber-h fg-black oxanium-font">@Html.DisplayFor(modelItem => district.DistrictName)</h2>
        <div class="district">
                <div class="left-content">
                    <div class="image-container">
                        <img src="@($"/Pictures/District/{Uri.EscapeDataString(district.DistrictName)}/{Uri.EscapeDataString(district.ImageOne)}")" alt="Image of @district.DistrictName" />
                    </div>
                </div>
                <div class="right-content">
                    <p class="description-text collapsed-text">@Html.DisplayFor(modelItem => district.Description)</p>
                <button class="read-more-button cyber-button-small bg-black fg-white" onclick="toggleDescription(this)">Read More</button>
                </div>
            
        </div>
        <br />
        <a href="@Url.Action("Details", "District", new { id = district.DistrictId })" class="cyber-button-small bg-red fg-white">Learn More</a>
    }
</div>

<script src="~/js/districts.js" asp-append-version="true"></script>